# Generated by Django 4.1.7 on 2023-02-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePictures', models.ImageField(blank=True, null=True, upload_to='ProfilePicture/Teacher/')),
                ('Address', models.CharField(max_length=40)),
                ('Mobile', models.CharField(max_length=20)),
                ('Status', models.BooleanField(default=False)),
                ('Salary', models.PositiveIntegerField(null=True)),
                ('Users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
