# Generated by Django 4.1.7 on 2023-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='ProfilePictures',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Email',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
