# Generated by Django 4.1.7 on 2023-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_remove_teacher_profilepictures_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='ProfilePictures',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePicture/Teacher/'),
        ),
    ]
