# Generated by Django 4.1.7 on 2023-02-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePicture/Student/'),
        ),
    ]
