# Generated by Django 4.1.7 on 2023-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_student_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
