# Generated by Django 4.1.7 on 2023-03-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_student_email_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_limit', models.IntegerField()),
            ],
        ),
    ]
