# Generated by Django 4.1.7 on 2023-02-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=50)),
                ('QuestionNumber', models.PositiveIntegerField()),
                ('TotalMarks', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.course')),
                ('Students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.PositiveIntegerField()),
                ('Question', models.CharField(max_length=600)),
                ('PossiblyAnswer1', models.CharField(max_length=200)),
                ('PossiblyAnswer2', models.CharField(max_length=200)),
                ('PossiblyAnswer3', models.CharField(max_length=200)),
                ('PossiblyAnswer4', models.CharField(max_length=200)),
                ('Answer', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.course')),
            ],
        ),
    ]
